### ISSUE TITLE
Create Main Fragment

### ISSUE THREAD

**Issue by VarunT11** [opencodeiiita/Collaborative-App#215]
## Issue Description
- Create a new **Fragment** and name it as `MainFragment`.
- Design the corresponding layout file of the Main Fragment. The items required on the Fragment are:
  - Heading
  - About Open Code
  - Open Code Banner
  - Button to visit Open Code Website from the Mobile's Browser. Note that the button should not perform any action on clicking it. 
- Create a `fragments` directory and add the Java file inside it only.
- You may test for the fragment's layout by adding it inside an activity. But the final Pull Request should contain only changes related to the new Fragment.

### Note
- Before starting work on this issue, update your `main` branch with the `main` branch of the main repository.
- Create a new branch for working on this issue and give it a meaningful name.
- Note that you must have completed the following issues in order to claim this issue:
  -  #1
  -  #10
  -  #80 
- If the above issues have not been completed, this issue will not be assigned to you.

**Comment by Puja-Saraf** [comment]
claim

**Comment by raghavgoel25** [comment]
Claim

**Comment by VarunT11** [comment]
@jalanprakhar Go for it!
