### ISSUE TITLE
Add the App Icon

### ISSUE THREAD

**Issue by VarunT11** [opencodeiiita/Collaborative-App#217]
## Issue Description
- Change the App Icon to the Open Code Logo.

### Note
- Before starting work on this issue, update your `main` branch with the `main` branch of the main repository.
- Create a new branch for working on this issue and give it a meaningful name.
- Note that you must have completed the following issues in order to claim this issue:
  -  #1
  -  #10
  -  #80 
- If the above issues have not been completed, this issue will not be assigned to you.

**Comment by Tanushree-coder** [comment]
claim
