### ISSUE TITLE
Change the App Name

### ISSUE THREAD

**Issue by VarunT11** [opencodeiiita/Collaborative-App#219]
## Issue Description
- Change the App Name to `Open Code Collab` or any similar name.

### Note
- Before starting work on this issue, update your `main` branch with the `main` branch of the main repository.
- Create a new branch for working on this issue and give it a meaningful name.
- Note that you must have completed the following issues in order to claim this issue:
  -  #1
  -  #10
  -  #80 
- If the above issues have not been completed, this issue will not be assigned to you.

**Comment by Tanushree-coder** [comment]
claim

**Comment by karankc23** [comment]
claim
