### ISSUE TITLE
Errors in main_fragment.xml

### ISSUE THREAD

**Issue by Tanushree-coder** [opencodeiiita/Collaborative-App#243]
There are some errors in the main_fragment layout due to which build is not running.
I would like to work on this issue, please assign this to me @VarunT11 .

**Comment by Tanushree-coder** [comment]
Layout margins are left blank

![image](https://user-images.githubusercontent.com/75807670/136664333-fd8ec43e-b6da-43f8-a2d8-3aa1bec53b1f.png)

**Comment by VarunT11** [comment]
@Tanushree-coder Go ahead and solve this bug!

**Comment by Tanushree-coder** [comment]
@VarunT11  plz check PR
