### ISSUE TITLE
Implement Navigation Component

### ISSUE THREAD

**Issue by VarunT11** [opencodeiiita/Collaborative-App#261]
## Issue Description
- Implement the **[Navigation Component](https://developer.android.com/guide/navigation/navigation-getting-started)** in the `MainActivity`.
- The Main Activity should open `SplashScreenFragment` first followed by the `MainFragment` after 1.5 seconds. Make sure to implement them in the `MainActivity` itself using the Navigation Component only.
- Add proper comments wherever required.

### Note
- Before starting work on this issue, update your `main` branch with the `main` branch of the main repository.
- Create a new branch from the `main` working on this issue and give it a meaningful name.
- Note that you must have completed the following issues to claim this issue:
  -  #1
  -  #10
  -  #80 
- If the above issues have not been completed, this issue will not be assigned to you.

**Comment by Puja-Saraf** [comment]
claim

**Comment by raghavgoel25** [comment]
claim

**Comment by VarunT11** [comment]
@Puja-Saraf The issue has been assigned to you!

**Comment by VarunT11** [comment]
@Puja-Saraf Let us know about the progress that you have made till now. Also, inform us if you are facing any issue with the same!
