### ISSUE TITLE
Create Project Class

### ISSUE THREAD

**Issue by VarunT11** [opencodeiiita/Collaborative-App#264]
## Issue Description
- Create a new **Class** inside the `classes` directory and name it as `Project`.
- Add the following attributes to the Class by using the specific type:
  - Name
  - GitHub Link
  - Mentors
  - Contributors
  - Number of Issues Opened
  - Number of Pull Requests Opened
  - Number of Pull Requests Merged
  - Number of Pull Requests Closed
- Create a constructor with the name.
- Use `ArrayList` of respective classes for the **Mentors** and **Contributors** attributes.
- Create getters and setters methods of all the attributes available.
- You can add more attributes that may be related to a Project in Open Code.

### Note
- Before starting work on this issue, update your `main` branch with the `main` branch of the main repository.
- Create a new branch from the `main` working on this issue and give it a meaningful name.
- Note that you must have completed the following issues to claim this issue:
  -  #1
  -  #10
  -  #80 
- If the above issues have not been completed, this issue will not be assigned to you.

**Comment by Monik09** [comment]
claim

**Comment by raghavgoel25** [comment]
claim

**Comment by diyawaghmare** [comment]
claim

**Comment by VarunT11** [comment]
@Monik09 The issue has been assigned to you!
