### ISSUE TITLE
Create item layout for Mentor RecyclerView

### ISSUE THREAD

**Issue by starboi02** [opencodeiiita/Collaborative-App#273]
## Issue Description
- Create a mentor_item.xml file and add the following views :
   - CardView as root layout
   - TextView (for mentor's name)
   - Circular ImageView (for mentor's image)
   - Icons (Facebook, Github and twitter)
- Make sure the layout is responsive and give proper IDs to the view.
- Maintain a proper 16dp vertical margin and 8dp horizontal margin for the root layout.

### Note
- Before starting work on this issue, update your `main` branch with the `main` branch of the main repository.
- Create a new branch for working on this issue and give it a meaningful name.
- Note that you must have completed the following issues to claim this issue:
  -  #1
  -  #10
  -  #80 
- If the above issues have not been completed, this issue will not be assigned to you.

**Comment by raghavgoel25** [comment]
claim
