### ISSUE TITLE
Create FetchApiSingleton Class

### ISSUE THREAD

**Issue by VarunT11** [opencodeiiita/Collaborative-App#299]
## Issue Description
- Create a new directory `api`.
- Inside this new directory, create a new class `FetchApiSingleton`.
- Add a private attribute `context` of type `Context`.
- Create a constructor of this class with the `context` attribute.
- Create a new `void` method `FetchApi` with the **Api Url** as the input in form of a string.
- This method should fetch the String Object from the Url using [**Volley**](https://developer.android.com/training/volley).
- Create two `void` methods `onJsonObjectFetch` and `onJsonArrayFetch` with `fetchedString` as a String Parameter. Convert the string to the respective object/array according to the method and leave the rest part of the method empty.
- When the String fetch is successful in the `FetchApi` method, check whether the string contains a JSON Object or a JSON Array. Accordingly, call the `onJsonObjectFetch` and `onJsonArrayFetch` methods.
- Test the working of the functions by implementing them in the `MainActivity`. Check whether the API Fetch is successful or not using the `Log` methods. Attach screenshots of this testing. Make sure to remove the changes made in testing in the final Pull Request.

### Note
- Before starting work on this issue, update your `main` branch with the `main` branch of the main repository.
- Create a new branch from the `main` working on this issue and give it a meaningful name.
- Note that you must have completed the following issues to claim this issue:
  -  #1
  -  #10
  -  #80 
- If the above issues have not been completed, this issue will not be assigned to you.

**Comment by raghavgoel25** [comment]
<img width="1440" alt="Screenshot 2021-10-12 at 4 04 52 PM" src="https://user-images.githubusercontent.com/75788719/136941001-f5a751d3-3c33-48ad-88e0-365d45d06ff5.png">
Name, Facebook, Github, Twitter.

**Comment by VarunT11** [comment]
@raghavgoel25 The issue has been assigned to you!
