### ISSUE TITLE
Add colors in colors.xml file

### ISSUE THREAD

**Issue by VarunT11** [opencodeiiita/Collaborative-App#300]
## Issue Description
 - Add colors in the `colors.xml` file. Following is the list of colors required:
   - Primary Color
   - Primary Light Color
   - Primary Dark Color
   - Secondary Color
   - Secondary Light Color
   - Secondary Dark Color
   - Accent Color
   - Text Heading Color
   - Text Primary Color
   - Text Secondary Color
   - Icon Color
- Choose suitable colors for the above types. Test the chosen colors by using them in the existing layout XML files and attach screenshots of them. In the final pull request, remove the changes in these files.

### Note
- Before starting work on this issue, update your `main` branch with the `main` branch of the main repository.
- Create a new branch from the `main` working on this issue and give it a meaningful name.
- Note that you must have completed the following issues to claim this issue:
  -  #1
  -  #10
  -  #80 
- If the above issues have not been completed, this issue will not be assigned to you.

**Comment by Tanushree-coder** [comment]
claim

**Comment by VarunT11** [comment]
@Tanushree-coder The issue has been assigned to you!
