### ISSUE TITLE
Change App Font

### ISSUE THREAD

**Issue by VarunT11** [opencodeiiita/Collaborative-App#308]
## Issue Description
- Download the `Montserrat` Font from the Internet.
- Change the default app font to `Montserrat`.
- Attach the screenshot after running the Application with the added font.

### Note
- Before starting work on this issue, update your `main` branch with the `main` branch of the main repository.
- Create a new branch from the `main` working on this issue and give it a meaningful name.
- Note that you must have completed the following issues to claim this issue:
  -  #1
  -  #10
  -  #80 
- If the above issues have not been completed, this issue will not be assigned to you.

**Comment by Tanushree-coder** [comment]
claim

**Comment by kaneki-ken260** [comment]
claim
