### ISSUE TITLE
Remove the default Action Bar from MainActivity

### ISSUE THREAD

**Issue by VarunT11** [opencodeiiita/Collaborative-App#309]
## Issue Description
- Remove the **ActionBar** from the `MainActivity`.
- Attach the screenshots after running the Application with the updated properties.
- You may encounter some bugs while running the Application. Try to fix those bugs too!

### Note
- Before starting work on this issue, update your `main` branch with the `main` branch of the main repository.
- Create a new branch from the `main` working on this issue and give it a meaningful name.
- Note that you must have completed the following issues to claim this issue:
  -  #1
  -  #10
  -  #80 
- If the above issues have not been completed, this issue will not be assigned to you.

**Comment by kaneki-ken260** [comment]
claim

**Comment by starboi02** [comment]
@kaneki-ken260 what's the progress? Also, let us know if you're stuck anywhere.

**Comment by starboi02** [comment]
@kaneki-ken260 issue unassigned!

**Comment by starboi02** [comment]
@raghavgoel25 assigned to you.

**Comment by raghavgoel25** [comment]
claim
