### ISSUE TITLE
Fix Splash Screen Open on Back Button Press

### ISSUE THREAD

**Issue by VarunT11** [opencodeiiita/Collaborative-App#310]
## Issue Description
- Perform the given steps:
  - Run the App
  - Allow the SplashScreen to navigate to MainFragment
  - Click Back Button
- Here, on pressing the Back Button, the App should have been closed, but it reopens the Splash Screen.
- Fix the above bug such that on pressing the back button, the Splash Screen Fragment does not open and the app closes.

### Note
- Before starting work on this issue, update your `main` branch with the `main` branch of the main repository.
- Create a new branch from the `main` working on this issue and give it a meaningful name.
- Note that you must have completed the following issues to claim this issue:
  -  #1
  -  #10
  -  #80 
- If the above issues have not been completed, this issue will not be assigned to you.

**Comment by Anushka1309** [comment]
Claim

**Comment by kaneki-ken260** [comment]
claim
