### ISSUE TITLE
Create layout for About Activity

### ISSUE THREAD

**Issue by starboi02** [opencodeiiita/Collaborative-App#315]
## Issue Description
- Create a about.xml file and add the following views :
   - Material AppBar layout
   - Toolbar (give heading "About Opencode" in the toolbar)
   - TextView (for content)
   - ImageView (for default image)
- Make sure the layout is responsive and give proper IDs to the view.
- Take reference from the [Opencode Website](https://opencodeiiita.github.io/Collaborative-Web/#about).
- Maintain a proper 16dp vertical margin and 8dp horizontal margin for the root layout.

### Note
- Before starting work on this issue, update your `main` branch with the `main` branch of the main repository.
- Create a new branch for working on this issue and give it a meaningful name.
- Note that you must have completed the following issues to claim this issue:
  -  #1
  -  #10
  -  #80 
- If the above issues have not been completed, this issue will not be assigned to you.

**Comment by jalanprakhar** [comment]
claim:(
