### ISSUE TITLE
Edit leaderboard_item.xml

### ISSUE THREAD

**Issue by starboi02** [opencodeiiita/Collaborative-App#337]
## Issue Description
- Include a new TextView to show ranks.
- Position it accordingly.

### Note
- Before starting work on this issue, update your `main` branch with the `main` branch of the main repository.
- Create a new branch from the `main` working on this issue and give it a meaningful name.
- Note that you must have completed the following issues to claim this issue:
  -  #1
  -  #10
  -  #80 
- If the above issues have not been completed, this issue will not be assigned to you.

**Comment by shashwat-mittal** [comment]
Claim
