### ISSUE TITLE
Implement API Fetch Callback Listener

### ISSUE THREAD

**Issue by VarunT11** [opencodeiiita/Collaborative-App#344]
## Issue Description
The `FetchApiSingleton` Class fetches the required JSON Object from the Internet but does not return it to the called method. This issue aims to return the result JSON Object back to the Called Method.

- Inside the `FetchApiSingleton` class, implement a Callback Listener method using Interface.
- This void Callback method should have `JSONObject` as a Parameter.
- This method should be called from the `onJsonObjectFetch` method.
- Test for the working of this callback method by implementing it in the `MainActivity` and attach screenshots of the same. Note that you should receive a **JSONObject** in the `MainActivity`. Once tested, remove the changes in the `MainActivity`. 

### Note
- Before starting work on this issue, update your `main` branch with the `main` branch of the main repository.
- Create a new branch from the `main` working on this issue and give it a meaningful name.
- Note that you must have completed the following issues to claim this issue:
  -  #1
  -  #10
  -  #80 
- If the above issues have not been completed, this issue will not be assigned to you.

**Comment by VarunT11** [comment]
@Ksathwik03 You have not completed the required 3 issues. Please complete it before claiming other issues in this repo.

**Comment by diyawaghmare** [comment]
claim

**Comment by shashwat-mittal** [comment]
Claim

**Comment by rohanbabbar04** [comment]
Claim

**Comment by Ksathwik03** [comment]
> @Ksathwik03 You have not completed all the required 3 issues. Please complete it before claiming other issues in this repo.

Sir i made prs for all the issues.
