### ISSUE TITLE
Add Heading Style

### ISSUE THREAD

**Issue by VarunT11** [opencodeiiita/Collaborative-App#346]
## Issue Description
- Add a common style for all the Headings of the Application.
- The style should contain the following items:
  - Text Size
  - Text Color
  - Text Style
  - Text Alignment
- Make sure to update it for both the dark and the light themes.

### Note
- Before starting work on this issue, update your `main` branch with the `main` branch of the main repository.
- Create a new branch from the `main` working on this issue and give it a meaningful name.
- Note that you must have completed the following issues to claim this issue:
  -  #1
  -  #10
  -  #80 
- If the above issues have not been completed, this issue will not be assigned to you.

**Comment by diyawaghmare** [comment]
claim

**Comment by VarunT11** [comment]
@diyawaghmare The issue has been assigned to you!
