### ISSUE TITLE
Fetch the List of Contributors from the contributor.xml file

### ISSUE THREAD

**Issue by VarunT11** [opencodeiiita/Collaborative-App#349]
## Issue Description
- Inside the `MainActivity.java` file, create a new private void method `FetchAppContributor` with 0 arguments.
- Inside this new method, fetch the list of Contributors from the `contributor.xml` file as an **ArrayList** of the `Participant` class.
- Test the working of the method by implementing it inside `onCreate` of `MainAcvtivity` using `Log` Functions. Attach screenshots of the same and remove this testing implementation in the Final Pull Request.

### Note
- Before starting work on this issue, update your `main` branch with the `main` branch of the main repository.
- Create a new branch from the `main` working on this issue and give it a meaningful name.
- Note that you must have completed the following issues to claim this issue:
  -  #1
  -  #10
  -  #80 
- If the above issues have not been completed, this issue will not be assigned to you.

**Comment by starboi02** [comment]
@Ksathwik03 kindly make a PR by today. Else the issue will be unassigned.
