### ISSUE TITLE
Add a Splash Screen to the project 

### ISSUE THREAD

**Issue by rohanbabbar04** [opencodeiiita/Collaborative-App#7]
Add a modified Android 12 version splash screen to the project

**Comment by naman-cr** [comment]
claim

**Comment by Kajal13081** [comment]
claim

**Comment by VarunT11** [comment]
@rohanbabbar04 This issue can be broken into multiple sub-issues. So instead of having a single issue for adding a Splash Screen, we would be having multiple issues for the same. Those issues would open soon, and you could then contribute by claiming them.
